
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tomsstory;MODE=MySQL
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop





